### ISSUE TITLE
Command line example

### ISSUE THREAD

**Issue by Sanyy** [imtbl/synapse-purge#1]
Hi,

I'm struggling to set (positional)arguments for the script.
synapse-purge.py: error: unrecognized arguments: <here_comes_pgsql_password>

I hope it is not a character issue.

Can you give me(us) an example how those (positional)arguments are passed to the script in the correct manner?

Thanks in advance

**Comment by Sanyy** [comment]
Thanks!

Got an error after successfully purging the rooms:

2020-04-03 22:52:22.412 | INFO     | __main__:main:234 - Purging local media older than: 2020-04-03 19:52:16...
2020-04-03 22:52:22.418 | INFO     | __main__:main:241 - 20 media to be cleaned...
2020-04-03 22:52:22.418 | INFO     | __main__:main:243 - (1/20) Processing media: 'tTdzBzBlNXMNFKKeCMepJQmk'...

Traceback (most recent call last):
  File "./synapse-purge.py", line 264, in <module>
    parser.exit(main(arguments))
  File "./synapse-purge.py", line 251, in main
    os.remove(path)
PermissionError: [Errno 13] Permission denied: '/var/lib/matrix-synapse/media/local_content/tT/dz/BzBlNXMNFKKeCMepJQmk'

The file has same permissions and owner as the others. (matrix-synapse:nogroup 644)
(Should i run this as root?)

Less important but i'm also confused about -d 3600 getting this:
2020-04-03 **22:23:28.370** | INFO     | __main__:main:207 - Purging events up to: 2020-04-03 **19:23:28**

Note to myself: used syntax
./synapse-purge.py "host=127.0.0.1 port=5432 user=UserOfDatabase dbname=NameOfDatabase password=PasswordOfBatabase connect_timeout=10" "v...e...r...y..._long_auth_token" -d 3600 -a http://127.0.0.1:8008/ -m /var/lib/matrix-synapse/media

**Comment by mserajnik** [comment]
> The file has same permissions and owner as the others. (matrix-synapse:nogroup 644) (Should i run this as root?)

synapse-purge needs write access on the media files and it’s up to you how you achieve this. On my server, for example, synapse and synapse-purge both run with UID 1000 (and this UID also owns the files), which makes it easy. Running as root _should_ be ok, but I’d recommend you rather adjust ownership/permissions instead.

> Less important but i'm also confused about -d 3600 getting this:  2020-04-03 22:23:28.370 | INFO     | main:main:207 - Purging events up to: 2020-04-03 19:23:28

I think this could be some UTC vs local time display issue; would that match up with your timezone if we assume that the _Purging events up to…_ displays UTC time?

**Comment by imtbl** [comment]
> Less important but i'm also confused about -d 3600 getting this:  2020-04-03 22:23:28.370 | INFO | main:main:207 - Purging events up to: 2020-04-03 19:23:28

It's now clarified in the output that we are displaying UTC time (because event timestamps are stored as UTC).

I'm closing this issue since there hasn't been any feedback regarding the permission issue; please reopen if necessary.
