### ISSUE TITLE
Upon purging, local_thumbnails seems to be unaffected

### ISSUE THREAD

**Issue by Recolate** [imtbl/synapse-purge#2]
Hello, 

This seems to be a great tool for my purposes, and it cleaned up my local_content quite well. That being said, local_thumbnails seems to be entirely unaffected. Is this by design? Or is there some way to clean up the thumbnails as well? 

Thanks!

**Comment by imtbl** [comment]
Thanks for the feedback. IIRC, we ran into some issues of it deleting room images and such because we can't really differentiate them from regular media thumbnails. But that might've been something else, I'm not entirely sure.

We'll look into it once we find some time.
