### ISSUE TITLE
The virtual environment found in /home/user/.cache/pypoetry/virtualenvs/synapse-purge-a7j9eOSB-py3.7 seems to be broken.

### ISSUE THREAD

**Issue by VanRobbin** [imtbl/synapse-purge#6]
The virtual environment found in /home/user/.cache/pypoetry/virtualenvs/synapse-purge-a7j9eOSB-py3.7 seems to be broken.
Recreating virtualenv synapse-purge-a7j9eOSB-py3.7 in /home/user/.cache/pypoetry/virtualenvs/synapse-purge-a7j9eOSB-py3.7
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/user/.cache/pypoetry/virtualenvs/synapse-purge-a7j9eOSB-py3.7/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']

**Comment by cryzed** [comment]
Do what the error says?

**Comment by imtbl** [comment]
Please refrain from opening issues that are solely related to your OS/Python setup and have nothing to do with synapse-purge itself. We do not provide support for these kinds of problems.

Thank you.
